name: e_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.8
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  country_picker: ^2.0.25
  font_awesome_flutter: ^10.7.0
  intl_phone_field: ^3.2.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  image_picker: ^1.0.8
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.2

  flutter_rating_bar: ^4.0.1
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/language/
    - assets/marketing/
    - assets/science/
    - assets/tech/


flutter_intl:
  enabled: true
